# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import get_events_pb2 as get__events__pb2


class GCalendarEventsStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetEvents = channel.unary_stream(
        '/MyHistoryDay.GCalendarEvents/GetEvents',
        request_serializer=get__events__pb2.EventsRequest.SerializeToString,
        response_deserializer=get__events__pb2.Event.FromString,
        )


class GCalendarEventsServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetEvents(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GCalendarEventsServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetEvents': grpc.unary_stream_rpc_method_handler(
          servicer.GetEvents,
          request_deserializer=get__events__pb2.EventsRequest.FromString,
          response_serializer=get__events__pb2.Event.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'MyHistoryDay.GCalendarEvents', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
