# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: get_events.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='get_events.proto',
  package='MyHistoryDay',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x10get_events.proto\x12\x0cMyHistoryDay\"\xc9\x01\n\rEventsRequest\x12\r\n\x05token\x18\x01 \x01(\t\x12\x15\n\rrefresh_token\x18\x02 \x01(\t\x12\x11\n\ttoken_uri\x18\x03 \x01(\t\x12\x11\n\tclient_id\x18\x04 \x01(\t\x12\x15\n\rclient_secret\x18\x05 \x01(\t\x12\x0e\n\x06scopes\x18\x06 \x01(\t\x12\x18\n\x10\x61pi_service_name\x18\x07 \x01(\t\x12\x13\n\x0b\x61pi_version\x18\x08 \x01(\t\x12\x16\n\x0erequested_date\x18\t \x01(\t\"6\n\x05\x45vent\x12\x18\n\x10\x65vent_start_time\x18\x01 \x01(\t\x12\x13\n\x0b\x65vent_title\x18\x02 \x01(\t2T\n\x0fGCalendarEvents\x12\x41\n\tGetEvents\x12\x1b.MyHistoryDay.EventsRequest\x1a\x13.MyHistoryDay.Event\"\x00\x30\x01\x62\x06proto3')
)




_EVENTSREQUEST = _descriptor.Descriptor(
  name='EventsRequest',
  full_name='MyHistoryDay.EventsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='MyHistoryDay.EventsRequest.token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='refresh_token', full_name='MyHistoryDay.EventsRequest.refresh_token', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='token_uri', full_name='MyHistoryDay.EventsRequest.token_uri', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='client_id', full_name='MyHistoryDay.EventsRequest.client_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='client_secret', full_name='MyHistoryDay.EventsRequest.client_secret', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='scopes', full_name='MyHistoryDay.EventsRequest.scopes', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='api_service_name', full_name='MyHistoryDay.EventsRequest.api_service_name', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='api_version', full_name='MyHistoryDay.EventsRequest.api_version', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='requested_date', full_name='MyHistoryDay.EventsRequest.requested_date', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=236,
)


_EVENT = _descriptor.Descriptor(
  name='Event',
  full_name='MyHistoryDay.Event',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='event_start_time', full_name='MyHistoryDay.Event.event_start_time', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='event_title', full_name='MyHistoryDay.Event.event_title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=238,
  serialized_end=292,
)

DESCRIPTOR.message_types_by_name['EventsRequest'] = _EVENTSREQUEST
DESCRIPTOR.message_types_by_name['Event'] = _EVENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EventsRequest = _reflection.GeneratedProtocolMessageType('EventsRequest', (_message.Message,), dict(
  DESCRIPTOR = _EVENTSREQUEST,
  __module__ = 'get_events_pb2'
  # @@protoc_insertion_point(class_scope:MyHistoryDay.EventsRequest)
  ))
_sym_db.RegisterMessage(EventsRequest)

Event = _reflection.GeneratedProtocolMessageType('Event', (_message.Message,), dict(
  DESCRIPTOR = _EVENT,
  __module__ = 'get_events_pb2'
  # @@protoc_insertion_point(class_scope:MyHistoryDay.Event)
  ))
_sym_db.RegisterMessage(Event)



_GCALENDAREVENTS = _descriptor.ServiceDescriptor(
  name='GCalendarEvents',
  full_name='MyHistoryDay.GCalendarEvents',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=294,
  serialized_end=378,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetEvents',
    full_name='MyHistoryDay.GCalendarEvents.GetEvents',
    index=0,
    containing_service=None,
    input_type=_EVENTSREQUEST,
    output_type=_EVENT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GCALENDAREVENTS)

DESCRIPTOR.services_by_name['GCalendarEvents'] = _GCALENDAREVENTS

# @@protoc_insertion_point(module_scope)
